#!/usr/bin/env bash
FABRIC_STARTER_REPOSITORY=${FABRIC_STARTER_REPOSITORY:-olegabu}
FABRIC_VERSION=${FABRIC_VERSION:-1.4.9}
FABRIC_STARTER_VERSION=${FABRIC_STARTER_VERSION:-stable}

docker build -t ${FABRIC_STARTER_REPOSITORY}/fabric-tools-extended:${FABRIC_STARTER_VERSION} -f ./fabric-tools-extended/Dockerfile  --build-arg FABRIC_VERSION=${FABRIC_VERSION} --build-arg FABRIC_STARTER_REPOSITORY=${FABRIC_STARTER_REPOSITORY} .
