#
# Copyright . All Rights Reserved.
#

version: '3.7'


services:
  ca:
    ports:
    - ${CA_PORT:-7054}:7054

  api:
    ports:
    - ${API_PORT:-4000}:3000

  www.peer:
    ports:
      - ${WWW_PORT:-80}:80