#
# Copyright . All Rights Reserved.
#

version: '3.7'

services:
    registry:
      container_name: docker-registry
      restart: always
      image: registry:2
      ports:
        - 5000:5000
      volumes:
        - ./data:/var/lib/registry
