kind: Secret
apiVersion: v1
metadata:
  name: genesis-block-{{ .Values.org }}
type: Opaque
data:
  {{ $genesisBlockPath := tpl .Values.genesisBlock . }}
  genesis.block: {{ .Files.Get $genesisBlockPath | b64enc }}
