// https://www.jvandemo.com/how-to-configure-your-angularjs-application-using-environment-variables/
(function (window) {
  window.__env = {
    // API url
    // apiUrl : 'http://dev.your-api.com',

    // Whether or not to enable debug mode
    // Setting this to false will disable console output
    // enableDebug : true
  };

  // THIS IS STUB FILE !!!
  // Real file should be generated by the server dynamically

  console.warn('THIS IS STUB env.js FILE!');
}(this));