registry:
  # Maximum number of times a password/secret can be reused for enrollment
  # (default: -1, which means there is no limit)
  maxEnrollments: -1

  # Contains user information which is used when LDAP is disabled
  identities:
    - name: adminca1
      pass: {{ .Values.enroll_secret }}
      type: client
      affiliation: ""
      maxenrollments: -1
      attrs:
        hf.Registrar.Roles: "client,user,peer,validator,auditor,ca"
        hf.Registrar.DelegateRoles: "client,user,validator,auditor"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.Registrar.Attributes: "*"
