/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.dns;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DnsChaincodeTest {
    @Test void appHasAGreeting() {

    }
}
