apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
  labels:
    app: rest-api
    name: rest-api
spec:
  selector:
    matchLabels:
      app: rest-api
  replicas: 1 {{/* ${{REPLICAS}} */}}
  template:
    metadata:
      #          annotations:
      #            sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: rest-api
    spec:
      volumes:
        - name: genesis-block
          secret:
            secretName: genesis-block-{{ .Values.org }}

        - name: certs
          projected:
            sources:
              - secret:
                  name: certs-{{ .Values.org }}
                  items:
                    {{- include "certificates.decode" (merge (deepCopy .) .Values.orderer) | nindent 12 }}
                    {{- include "certificates.decode" (merge (deepCopy .) .Values.peer)    | nindent 12 }}

      containers:
        - name: rest
          ports:
            - name: rest-api-port
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          volumeMounts:
            - name: certs
              mountPath: /etc/hyperledger/crypto-config #/ordererOrganizations/${DOMAIN}
            - name: genesis-block
              mountPath: /etc/hyperledger/channel-artifacts

          image: >-
            {{ tpl .Values.images.fabric_starter_rest . }}
{{/*            ${IMAGE_PATH}@sha256:${IMAGE_TAG}*/}}

          {{/*          command: ["ls", "-l", "/etc/hyperledger/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com"]*/}}
          command: ["npm", "start"]

          envFrom:
            - configMapRef:
                name: common
          env:
{{/*            - name: DB_PASSWORD*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: db-password*/}}
{{/*                  key: password*/}}
            - name: ORDERER_POSTGRESLEDGER_DATASOURCENAME
              value: user=$(DB_USERNAME) dbname=$(DB_NAME) password=$(DB_PASSWORD) host=$(DB_HOST) port=$(DB_PORT) sslmode=disable

            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/msp
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/ca.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/orderers/orderer.{{ .Values.domain }}/tls/server.key
            - name: ORDERER_CA
              value: /etc/hyperledger/crypto-config/ordererOrganizations/{{ .Values.domain }}/tlsca/tlsca.{{ .Values.domain }}-cert.pem

            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/tls/ca.crt
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/crypto-config/peerOrganizations/{{ .Values.org }}.{{ .Values.domain }}/peers/peer0.{{ .Values.org }}.{{ .Values.domain }}/msp


#          resources:
#            limits:
#              cpu: ${CPULIMIT}
#              memory: ${MEMORYLIMIT}
#            requests:
#              cpu: ${CPUREQUEST}
#              memory: ${MEMORYREQUEST}
          #              readinessProbe:
          #                httpGet:
          #                  path: /health/check
          #                  port: 8080
          #                initialDelaySeconds: 10
          #              livenessProbe:
          #                httpGet:
          #                  path: /health/check
          #                  port: 8080
          #                initialDelaySeconds: 10
