kind: Service
apiVersion: v1
metadata:
  name: dns
  namespace:  {{ .Values.NAMESPACE }}
spec:
  ports:
    - name: chaincodeport
      protocol: TCP
      port: 9999
      targetPort: 9999
  selector:
    app: dns