apiVersion: v1
kind: Secret
metadata:
  name: certs-{{ .Values.org }}
type: Opaque

{{ $org := .Values.org }}
{{ $domain := .Values.domain }}

data:
  {{ include "certificates.encode" (merge (deepCopy .) .Values.peer) }}
  {{ include "certificates.encode"  (merge (deepCopy .) .Values.orderer) }}

{{/*  {{ range $dir := .Values.certDirs.orderer  }}*/}}
{{/*    {{ range $path, $_ := $.Files.Glob (printf "%s%s" (tpl $dir $) "/*" ) }}*/}}
{{/*      {{ replace "/" "__" $path | replace "@" "___" }}: {{ $.Files.Get $path | b64enc }}*/}}
{{/*    {{ end }}*/}}
{{/*  {{ end }}*/}}

