{{ range $ordererName := split "," .Values.ordererNames }}

{{- $ordererValues := dict "ordererName" $ordererName "domain" $.Values.domain "ordererDomain" $.Values.ordererDomain "certificatePathes" $.Values.orderer.certificatePathes "Values" (dict "ordererName" $ordererName) -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: orderer-certs-{{ include "orderer.nameDomain" $ordererValues }}
type: Opaque
data:

  {{ include "certificates.encode"  (mergeOverwrite (deepCopy $) $ordererValues ) }}
{{/*  {{ include "certificates.encode"  (merge (deepCopy .) .Values.orderer) }}*/}}


{{ end }}
